import { Vehicle } from "@/types";

export const VEHICLES: Vehicle[] = [
  {
    name: "Hyundai Venue 2023",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 5,
    luggage: "3 Bags",
    price: "₹2500/day",
    tags: ["Best SUV", "Manual", "Diesel"],
    suitableFor: "Comfortable city driving and highway cruises",
    imageName: "venue-rental.webp",
  },
  {
    name: "Maruti Ertiga New",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 7,
    luggage: "4 Bags",
    price: "₹3000/day",
    tags: ["Family Favourite", "CNG+Petrol"],
    suitableFor: "Perfect for family road trips and group travels",
    imageName: "ertiga-self-drive.webp",
  },
  {
    name: "Maruti Suzuki Swift",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "₹1500/day",
    tags: ["Best Value", "Manual", "Petrol"],
    suitableFor: "Compact city rides and easy parking",
    imageName: "swift-rental.jpg",
  },
  {
    name: "Maruti New Dzire 2023",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "₹2000/day",
    tags: ["Most Popular", "CNG+Petrol"],
    suitableFor: "Affordable premium sedan for daily commuting",
    imageName: "dzire-rental.jpg",
  },
  {
    name: "Vitara Brezza 2023",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "3 Bags",
    price: "₹2500/day",
    tags: ["Weekend Special", "Compact SUV"],
    suitableFor: "High ground clearance, reliable off-road capability",
    imageName: "brezza-rental.jpg",
  },
  {
    name: "Hyundai Nios",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "₹1800/day",
    tags: ["Budget Friendly", "Petrol"],
    suitableFor: "Super fuel-efficient hatchback for local rides",
    imageName: "nios-rental.webp",
  },
  {
    name: "Hyundai Creta",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 5,
    luggage: "4 Bags",
    price: "₹3300/day",
    tags: ["Premium SUV", "Diesel"],
    suitableFor: "Premium luxury ride with spacious interiors",
    imageName: "creta-rental.png",
  },
  {
    name: "Kia Seltos",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "3 Bags",
    price: "₹3000/day",
    tags: ["Luxury Feel", "Petrol"],
    suitableFor: "Tech-loaded SUV for premium style statements",
    imageName: "seltos-rental.jpg",
  },
  {
    name: "Toyota Innova Crysta",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 7,
    luggage: "5 Bags",
    price: "₹3600/day",
    tags: ["Executive Choice", "Diesel"],
    suitableFor: "Chauffeur comfort and unmatched long drive stability",
    imageName: "innova-rental.jpg",
  },
  {
    name: "Maruti Suzuki Ciaz",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "3 Bags",
    price: "₹2200/day",
    tags: ["Premium Sedan", "Petrol"],
    suitableFor: "Elegant long-wheelbase sedan for executive comfort",
    imageName: "ciaz-rental.jpg",
  },
  {
    name: "Tata Tiago",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "₹1200/day",
    tags: ["Eco Saver", "Petrol"],
    suitableFor: "Affordable hatchback for easy city navigation",
    imageName: "tiago-rental.jpg",
  },
  {
    name: "Maruti Suzuki Baleno",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "₹1800/day",
    tags: ["Hatchback Premium", "Petrol"],
    suitableFor: "Premium hatchback comfort for city and highway",
    imageName: "baleno-rental.jpg",
  },
];
