import { Vehicle } from "@/types";

export const VEHICLES: Vehicle[] = [
  {
    name: "Maruti Suzuki Swift",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "Starting @ ₹1,500/day",
    tags: ["Best Value", "Manual", "Petrol"],
    suitableFor: "Daily commute, solo trips, or city tours",
    imageName: "swift-rental.webp",
  },
  {
    name: "Maruti Suzuki Baleno",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "2 Bags",
    price: "Starting @ ₹1,800/day",
    tags: ["Premium Hatchback", "Manual", "Petrol"],
    suitableFor: "Premium local travel or business meetings",
    imageName: "baleno-rental.webp",
  },
  {
    name: "Maruti Suzuki Brezza",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    luggage: "3 Bags",
    price: "Starting @ ₹2,200/day",
    tags: ["Weekend Special", "Compact SUV"],
    suitableFor: "Local driving or weekend family getaways",
    imageName: "brezza-rental.webp",
  },
  {
    name: "Maruti Suzuki Ertiga",
    transmission: "Manual",
    fuel: "CNG",
    seats: 7,
    luggage: "4 Bags",
    price: "Starting @ ₹2,800/day",
    tags: ["Family Favourite", "Most Booked", "CNG"],
    suitableFor: "Family trips, picnics, or group outstations",
    imageName: "ertiga-self-drive.webp",
  },
  {
    name: "Toyota Innova Crysta",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 7,
    luggage: "5 Bags",
    price: "Starting @ ₹3,800/day",
    tags: ["Premium SUV", "Outstation Ready", "Diesel"],
    suitableFor: "Corporate travel, airport transfers, or luxury trips",
    imageName: "innova-rental.webp",
  },
  {
    name: "Mahindra Scorpio-N",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 7,
    luggage: "4 Bags",
    price: "Starting @ ₹3,000/day",
    tags: ["Off-Road Special", "Diesel"],
    suitableFor: "Rough terrains, family adventures, or highway runs",
    imageName: "scorpio-rental.webp",
  },
];
