export const siteConfig = {
  name: "DriveMitra",
  phone: "+918889539174",
  phoneDisplay: "+91 88895 39174",
  whatsapp: "+918889539174",
  whatsappDisplay: "+91 88895 39174",
  email: "bhopalservice998@gmail.com",
  address: "Plot No. 12, dig bunglow chouraha Bhopal, Madhya Pradesh 462038",
  workingHours: "24/7 Open",
  supportHours: "24/7 Dedicated Call & WhatsApp Support",
  googleMapsUrl: "https://maps.google.com",
  rating: "4.8",
  ratingCount: "2,450",
  url: "https://drive-mitra-lake.vercel.app",
  metaTitle: "Self Drive Car in Bhopal | Self Drive Car Rental Bhopal | Drive Mitra",
  metaDescription: "Book self drive cars in Bhopal without driver. Ertiga, SUV and automatic cars available for hourly, daily and weekend rental.",
};
